S = COMMITHEADER <WHITESPACE> AUTHOR <WHITESPACE> DATE MESSAGE DIFF;

COMMITHEADER = 'commit' <WHITESPACE> HASH;

HASH = #'[a-z0-9]{40}';

AUTHOR = 'Author:' <WHITESPACE> NAME <WHITESPACE> EMAIL; 

EMAIL = #'(?s)<.+>'; 

NAME = #'([a-z0-9]|\.)+';

WHITESPACE =  #'(\s|\n)+';

DATE = 'Date:' <WHITESPACE> #'.*\n';

MESSAGE = #'(.|\n)*?(?=diff --git)';

DIFF = DIFFLINE INDEX MINUS PLUS AT #'(.|\n)*';

DIFFLINE = #'diff --git.*\n'

INDEX = #'index.*\n'

MINUS = #'---.*\n'

PLUS = #'\+\+\+.*\n'

AT = #'@.*\n'