S = COMMIT|Epsilon;COMMIT = COMMITHEADER WHITESPACE AUTHORHEADER DIFF; COMMITHEADER = 'commit' WHITESPACE HASH'; AUTHORHEADER = 'Author:' WHITESPACE NAME WHITESPACE EMAIL; NAME = #'[a-z0-9]+'; EMAIL =  '<' NAME '@' NAME '>';WHITESPACE = #'\\s+'HASH = #'[a-z0-9]{40}';DIFF = #'.*'
